Dev/ranger integration
ThalesGroup/opendistro-security pull request #3
Opened 2020-08-04 05:58 UTC by divyansh-jain-guavus

2020-08-04 12:06 UTC, goelrajat requested changes

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/dlic/auth/http/kerberos/HTTPSpnegoAuthenticator.java
> +                    log.info ("username : " + username + " will be used for " + ((SimpleUserPrincipal) principal).getName());
Change to debug log

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/dlic/auth/http/kerberos/HTTPSpnegoAuthenticator.java
> +                    e.printStackTrace();
Stack trace should be logged with logger message. Also, in case of exception, we should continue using user name value as original username.

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/dlic/auth/http/kerberos/HTTPSpnegoAuthenticator.java
> +                    e.printStackTrace();
Stack trace should be logged with logger message. Also, if the exception is related to incorrect file content or missing file, then we should propagate exception upwards so that elasticsearch node doesn't start till the problem is fixed. This config should be optional, if the config is not set then we should just continue without it.

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/dlic/auth/ldap/util/ConfigConstants.java
> +    public static final String LDAP_GROUP_NAME_ATTR = "groupname_attribute";
These are not being used anywhere. Can be removed.

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
> +        log.info("Evaluator = " + settings.get(ConfigConstants.OPENDISTRO_SECURITY_EVALUATOR));
Change to debug log

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
> +        }
Why not multiple catch blocks in the first try itself ?
Also, we should use logger itself for printing exception rather than 'ex.printStackTrace()'. There's no use printing just exception name in debug log. Also, we need to think which all exceptions are just warning and its ok to continue processing versus which are errors and we should propagate it upwards. Currently the code is treating everything as warning.

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/IndexBaseConfigurationRepository.java
> +                                    LOGGER.error("Caught exception in load config . Please investigate: "
Change to warning instead of error

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
> +            log.info("Evaluate permissions for user: {}", user.getName());
This can be changed to debug log

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityFlsDlsIndexSearcherWrapper.java
> +            final ComplianceIndexingOperationListener ciol, final ComplianceConfig complianceConfig, final Evaluator evaluator) {
We could have kept the interface/abstract class name as PrivilegesEvaluator only and avoided making changes in so many files. The concrete implementation of this could have been named 'DefaultPrivilegesEvaluator'

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityIndexSearcherWrapper.java
> +    private final Evaluator evaluator;
We could have kept the interface/abstract class name as PrivilegesEvaluator only and avoided making changes in so many files. The concrete implementation of this could have been named 'DefaultPrivilegesEvaluator'

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/Evaluator.java
> +public interface Evaluator extends ConfigurationChangeListener {
We could have kept the interface class name as PrivilegesEvaluator only and avoided making changes in so many files. The concrete implementation of this could have been named 'DefaultPrivilegesEvaluator'

2020-08-04 12:06 UTC, goelrajat commented on src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/EvaluatorResponse.java
> +public interface EvaluatorResponse {
We could have kept the interface/abstract class name as PrivilegesEvaluatorResponse only and avoided making changes in so many files. The concrete implementation of this could have been named 'DefaultPrivilegesEvaluatorResponse'

2020-08-06 05:49 UTC, goelrajat commented on src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/Evaluator.java
> +    Set<String> getAllConfiguredTenantNames();
Do we need these APIs in this interface definition ? If both default implementation of Privileges Evaluator and Ranger implementation are using the same code for these APIs then we can add these API defnitions in abstract class 'AbstractEvaluator' only.

2020-08-08 23:31 UTC, divyansh-jain-guavus commented on src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/IndexBaseConfigurationRepository.java
> +                                    LOGGER.error("Caught exception in load config . Please investigate: "
this is not needed, will remove it

2020-08-15 12:22 UTC, closed without merging